-- Update script for PSC Issues Database
-- This updates the database from the original schema to remove password requirements
-- and reset Jamie Briggs' password to PSC1

USE psc_issues;

-- Update Jamie Briggs' password from 'PSCAdmin2024!' to 'PSC1'
-- Using the working hash generated by test_password.php
UPDATE `users` 
SET `password_hash` = '$2y$10$XjFfxcaQ4jIu813j50X2jOMou/vnN7Mr52/1Eya3qQ2UBP0MU2p4u', 
    `updated_at` = NOW()
WHERE `username` = 'jamiebriggs' AND `role` = 'ADMIN';

-- Verify the update was successful
SELECT id, full_name, username, role, must_change_password, updated_at 
FROM users 
WHERE username = 'jamiebriggs';

-- Display confirmation message
SELECT 'Password updated successfully for Jamie Briggs (jamiebriggs)' AS status;